INSERT OR IGNORE INTO products (id, name, category, price, compare_at, sizes, colors, verse, tagline, tag, description, images, created_at) VALUES
('lion-of-judah-tee', 'Lion of Judah Tee', 'Tees', 1299, NULL,
 '["S","M","L","XL","XXL"]', '[{"name":"Black","hex":"#151210"}]',
 'Revelation 5:5', NULL, 'New',
 'Oversized heavyweight tee with a bold ''Lion of Judah'' back print — a crowned lion over a dusk skyline, with the full verse lettered beside it. Drop-shoulder fit in 240 GSM cotton fleece.',
 '["/products/lion-of-judah-tee-1.jpg","/products/lion-of-judah-tee-2.jpg","/products/lion-of-judah-tee-3.jpg"]',
 '2026-09-10T00:00:00.000Z'),

('heavenly-influencer-tee', 'Heavenly Influencer Tee', 'Tees', 1299, NULL,
 '["S","M","L","XL","XXL"]', '[{"name":"Royal Blue","hex":"#2c3ea3"}]',
 'Matthew 5:16', NULL, 'New',
 'Bold varsity-style ''Heavenly Influencer'' print with ''Let your light shine before others'' lettered beneath. Oversized fit, heavyweight cotton fleece.',
 '["/products/heavenly-influencer-tee-1.jpg","/products/heavenly-influencer-tee-2.jpg","/products/heavenly-influencer-tee-3.jpg"]',
 '2026-09-10T00:00:00.000Z'),

('kingdom-mindset-tee', 'Kingdom Mindset Tee', 'Tees', 1299, NULL,
 '["S","M","L","XL","XXL"]', '[{"name":"Red","hex":"#a3242c"}]',
 NULL, 'Kingdom Mindset', 'New',
 'A crest-style badge graphic with a crown and laurel wreath, screen-printed front and center on an oversized, heavyweight tee.',
 '["/products/kingdom-mindset-tee-1.jpg","/products/kingdom-mindset-tee-2.jpg","/products/kingdom-mindset-tee-3.jpg"]',
 '2026-09-10T00:00:00.000Z'),

('grace-changed-my-story-tee', 'Grace Changed My Story Tee', 'Tees', 1299, NULL,
 '["S","M","L","XL","XXL"]', '[{"name":"Royal Blue","hex":"#2c3ea3"}]',
 NULL, 'Grace Changed My Story', 'New',
 'Hand-lettered sticker-style back graphic with a small cross accent — a quiet testimony worn loud. Oversized heavyweight fit.',
 '["/products/grace-changed-my-story-tee-1.jpg","/products/grace-changed-my-story-tee-2.jpg","/products/grace-changed-my-story-tee-3.jpg"]',
 '2026-09-10T00:00:00.000Z'),

('jesus-little-princess-tee', 'Jesus'' Little Princess Tee', 'Tees', 1199, NULL,
 '["S","M","L","XL"]', '[{"name":"Cream","hex":"#f3ecd8"}]',
 'Psalm 139:14', NULL, 'New',
 'A soft illustrated graphic with sunflowers on a cream tee, paired with ''I am fearfully and wonderfully made.'' Oversized, heavyweight cotton.',
 '["/products/jesus-little-princess-tee-1.jpg","/products/jesus-little-princess-tee-2.jpg","/products/jesus-little-princess-tee-3.jpg"]',
 '2026-09-10T00:00:00.000Z'),

('philippians-4-7-tee', 'Philippians 4:7 Tee', 'Tees', 1199, NULL,
 '["S","M","L","XL","XXL"]', '[{"name":"Cream","hex":"#f3ecd8"}]',
 'Philippians 4:7', NULL, 'New',
 'The full verse lettered vertically down the back in clean serif type — ''And the peace of God, which surpasses all understanding, will guard your hearts and minds through Christ Jesus.''',
 '["/products/philippians-4-7-tee-1.jpg","/products/philippians-4-7-tee-2.jpg","/products/philippians-4-7-tee-3.jpg"]',
 '2026-09-10T00:00:00.000Z'),

('i-ace-my-race-tee', 'I Ace My Race Tee', 'Tees', 1299, NULL,
 '["S","M","L","XL","XXL"]', '[{"name":"Black","hex":"#151210"}]',
 NULL, 'I Ace My Race By God''s Grace', 'New',
 'Hand-painted lettering in pink and gold with a crown accent on jet black. Oversized, heavyweight fit for everyday wear.',
 '["/products/i-ace-my-race-tee-1.jpg","/products/i-ace-my-race-tee-2.jpg","/products/i-ace-my-race-tee-3.jpg"]',
 '2026-09-10T00:00:00.000Z'),

('plain-eggplant-tee', 'The Essentials Tee — Eggplant', 'Tees', 899, NULL,
 '["S","M","L","XL","XXL"]', '[{"name":"Eggplant","hex":"#3c1f30"}]',
 NULL, 'No print. Just presence.', 'New',
 'The blank canvas of the collection — same oversized, heavyweight 240 GSM cotton fleece as every printed piece, in a deep eggplant tone. Understated, versatile, built to layer.',
 '["/products/plain-eggplant-tee-1.jpg","/products/plain-eggplant-tee-2.jpg","/products/plain-eggplant-tee-3.jpg"]',
 '2026-09-10T00:00:00.000Z');
